project:
  type: website
  output-dir: docs

website:
  title: "DOAH"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Customer Analysis" 
      - CusSeg.qmd
      - text: "Conclusion"
      - Conclusion.qmd 

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

