---
title: "Doah's Website"
---

# Welcome to my website :)

Hello! This page is dedicated to those who are interested in exploring the insurance market. Follow along as I embark on this interesting project to analyze user demographics and establish criteria for insurance policies (products).

## Self-Introduction

To start off, here is a brief introduction about myself. My name is Doah Kim, a penultimate studying Economics at NUS. I'm also taking up Chinese language and Communications and New Media as a minor. As you might have guessed, I am interested in a lot of things. I am particularly interested in how I can contribute to a wider range of people with the work I do. I like to explore the world around me, and I'm a peoples person who loves to interact with those around me. More from my background, I am from Korea, lived in Singapore during my elementary school years, and came back for my study in university. Some of my hobbies are rock climbing, café-hopping, and watching dramas!

## Why is this important?

In today's rapidly evolving financial landscape, the ability to accurately assess and manage loan sanctions is more critical than ever for financial institutions. This website aims to delve into the intricate relationships between demographic factors and loan sanction amounts, leveraging extensive data from our two primary datasets: customer segmentation and loan sanction records. This analysis is not just about numbers; it's about understanding the people behind these numbers—their backgrounds, behaviors, and financial needs.

Financial inclusivity and risk management are at the heart of modern banking practices.By examining how variables such as age, gender, income level, and employment status influence loan amounts, we can uncover valuable insights that help financial institutions refine their risk assessment models and tailor their products to meet the diverse needs of their clientele. Such targeted analytics not only boost the profitability of banks by reducing default rates but also enhance customer satisfaction by providing more personalized financial solutions.

This project is driven by a broader aim to contribute to economic stability and growth. According to studies by entities like the Federal Reserve and the McKinsey Global Institute, well-informed loan sanctioning can unlock new credit markets, thus stimulating economic activities and supporting small and medium-sized enterprises—the backbone of our economy.

## Dataset Variable Description

```{=html}
<iframe height="700" width="100%" frameborder="no" src="https://doah240315-2.shinyapps.io/dataset/"> </iframe>
```
## Exploring Demographics

Below are the demographic details of the insurance applicants and owners, for a better understanding of data

```{=html}
<iframe height="700" width="100%" frameborder="no" src="https://doah240315.shinyapps.io/kdfinal1/"> </iframe>
```
