project:
  type: website
  output-dir: finalproject

website:
  title: "KimDoah"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

